### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by KBalane** [Qnx-EmergingTech/WeatheringWithU#22]
Add functionality of search bar.
Search for diff. Philippine cities. and redirect /:city

**Comment by franzsuperales** [comment]
Location API:
7R07int7J1HS4xoJr5xYG515G7SUQvGJ
 
Sample request:
http://dataservice.accuweather.com/locations/v1/cities/autocomplete?apikey=7R07int7J1HS4xoJr5xYG515G7SUQvGJ&q=Bacoor
